# Default values for sample-api
replicaCount: 2

image:
  repository: sample-api
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  hosts:
    - host: app.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80

# Rollout configuration
rollout:
  enabled: true
  strategy: blueGreen # or canary

# Blue/Green specific
blueGreen:
  autoPromotionEnabled: false
  scaleDownDelaySeconds: 30
  prePromotionAnalysis:
    enabled: true

# Canary specific
canary:
  steps:
    - setWeight: 20
    - pause: { duration: 2m }
    - setWeight: 50
    - pause: { duration: 2m }
    - setWeight: 100
  analysis:
    enabled: true
    successRate: 95
    latencyP99: 500

# Prometheus metrics
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    path: /metrics

# Application configuration
app:
  config:
    environment: "development"
    logLevel: "INFO"
    version: "1.0.0"
