replicaCount: 1

image:
  repository: ghcr.io/mrthehavok/sample-api
  tag: "latest"
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  name: ""

rbac:
  create: false

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 8000

ports:
  http:
    name: http
    containerPort: 8000

resources:
  limits: {}
  requests: {}

env: []
extraEnvFrom: []

probes:
  liveness:
    enabled: true
    path: /health/live
    initialDelaySeconds: 5
    periodSeconds: 10
  readiness:
    enabled: true
    path: /health/ready
    initialDelaySeconds: 5
    periodSeconds: 10
  startup:
    enabled: false
    path: /health/startup
    failureThreshold: 30
    periodSeconds: 10

metrics:
  enabled: true
  path: /metrics
  scrape:
    enabled: true
    interval: 15s
    port: http
  serviceMonitor:
    enabled: false
  annotations: {}

rollouts:
  enabled: true
  strategy: canary # Options: blueGreen | canary
  canary:
    enabled: true
    trafficRouting:
      nginx:
        stableIngress: { { include "sample-api.fullname" . } }
    # Example:
    # steps:
    #   - setWeight: 20
    #   - pause: {}
    steps:
      - setWeight: 20
      - pause: {}
  blueGreen:
    enabled: false
    autoPromotionEnabled: false
    autoPromotionSeconds: 0
  rollbackWindow:
    revisions: 10
  restartAt: ""

config:
  enabled: false
  data: {}

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Canary"
  hosts:
    - host: sample-api.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}

labels: {}
annotations: {}
