## Staging environment overrides
config:
  environment: "staging"
  logLevel: "INFO"
  debug: false
  features:
    slowEndpoint: true
    slowEndpointDelay: 3
    errorRate: 0

rollout:
  replicas: 2
  strategy: canary
  canary:
    steps:
      - setWeight: 20
      - pause: { duration: 1m }
      - setWeight: 50
      - pause: { duration: 1m }
      - setWeight: 100

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
