apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
data:
  # Enable Prometheus metrics
  enable-prometheus-metrics: "true"

  # Custom timeouts
  proxy-connect-timeout: "600"
  proxy-send-timeout: "600"
  proxy-read-timeout: "600"

  # Body size
  proxy-body-size: "10m"

  # Rate limiting
  limit-rate: "0"
  limit-rate-after: "0"

  # SSL/TLS
  ssl-protocols: "TLSv1.2 TLSv1.3"

  # Logging
  log-format-upstream:
    '{"time": "$time_iso8601", "remote_addr": "$proxy_protocol_addr",
    "x_forwarded_for": "$proxy_add_x_forwarded_for", "request_id": "$req_id",
    "remote_user": "$remote_user", "bytes_sent": $bytes_sent, "request_time": $request_time,
    "status": $status, "vhost": "$host", "request_proto": "$server_protocol",
    "path": "$uri", "request_query": "$args", "request_length": $request_length,
    "duration": $request_time, "method": "$request_method", "http_referrer": "$http_referer",
    "http_user_agent": "$http_user_agent", "upstream_addr": "$upstream_addr",
    "upstream_response_time": "$upstream_response_time", "upstream_status": "$upstream_status"}'
---
apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx-controller-metrics
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 10254
      targetPort: 10254
      protocol: TCP
  selector:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/component: controller
