# Default StorageClass with immediate binding
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-ssd
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
volumeBindingMode: Immediate
allowVolumeExpansion: true
---
# StorageClass for persistent data
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: persistent-data
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
reclaimPolicy: Retain
