apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: sample-api-error-rate
  namespace: sample-app
spec:
  metrics:
    - name: error-rate
      interval: 1m
      count: 3
      successCondition: result[0] < 0.05
      failureCondition: result[0] > 0.10
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring:9090
          query: |
            sum(rate(http_requests_total{status=~"5.."}[1m]))
            /
            sum(rate(http_requests_total[1m]))
