apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  datasources.yaml: |
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://kube-prometheus-stack-prometheus:9090
        isDefault: true
        jsonData:
          timeInterval: 15s
      - name: Alertmanager
        type: alertmanager
        access: proxy
        url: http://kube-prometheus-stack-alertmanager:9093
        jsonData:
          implementation: prometheus
