apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://argoproj.github.io/argo-helm
    chart: argo-cd
    targetRevision: "6.11.0" # Pinning to a specific stable version
    helm:
      releaseName: argocd
      valuesObject:
        installCRDs: false
        controller:
          replicas: 1
        server:
          replicas: 1
        repoServer:
          replicas: 1
        redis:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
