# Values for umbrella chart "monitoring" to configure dependency kube-prometheus-stack
kube-prometheus-stack:
  fullnameOverride: kube-prometheus-stack

  defaultRules:
    create: true

  grafana:
    enabled: true
    adminUser: admin
    adminPassword: admin
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: {}
      hosts:
        - grafana.local
      path: /
      pathType: Prefix
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 200m
        memory: 256Mi
    sidecar:
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        folder: /
        searchNamespace: ALL
      datasources:
        enabled: true
        defaultDatasourceEnabled: false

  alertmanager:
    enabled: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: {}
      hosts:
        - alertmanager.local
      paths:
        - /
      pathType: Prefix
    alertmanagerSpec:
      retention: 120h
    config:
      global: {}
      route:
        receiver: "dev-null"
        group_wait: 10s
        group_interval: 1m
        repeat_interval: 1h
      receivers:
        - name: "dev-null"
          webhook_configs:
            - url: "http://127.0.0.1:9091/"
              send_resolved: true
    resources:
      requests:
        cpu: 25m
        memory: 64Mi
      limits:
        cpu: 100m
        memory: 128Mi

  prometheus:
    enabled: true
    service:
      type: ClusterIP
    ingress:
      enabled: true
      ingressClassName: nginx
      annotations: {}
      hosts:
        - prometheus.local
      paths:
        - /
      pathType: Prefix
    prometheusSpec:
      retention: 12h
      # Use emptyDir for local dev by omitting storageSpec
      resources:
        requests:
          cpu: 200m
          memory: 256Mi
        limits:
          cpu: 600m
          memory: 768Mi
      serviceMonitorSelectorNilUsesHelmValues: false
      serviceMonitorSelector: {}
      serviceMonitorNamespaceSelector: {}
      podMonitorSelector: {}
      podMonitorNamespaceSelector: {}
      ruleNamespaceSelector: {}

  kube-state-metrics:
    enabled: true

  prometheus-node-exporter:
    enabled: true

  kubeApiServer:
    enabled: true

  kubeControllerManager:
    enabled: true

  kubeEtcd:
    enabled: false # Minikube may not expose etcd metrics by default

  kubeScheduler:
    enabled: true

  kubeProxy:
    enabled: true

  coreDns:
    enabled: true
