apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/mrthehavok/k8s-observable-rollouts
    targetRevision: HEAD
    path: infrastructure/argocd/applications
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# --- Example Child App (commented out) ---
# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: example-app
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/mrthehavok/k8s-observable-rollouts
#     path: helm-charts/example-app
#     targetRevision: HEAD
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: example-app
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#     - CreateNamespace=true
