{{- if and .Values.rollout.enabled (eq .Values.rollout.strategy "blueGreen") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sample-api.fullname" . }}-preview
  labels:
    {{- include "sample-api.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sample-api.selectorLabels" . | nindent 4 }}
{{- end }}