name: "CI: Lint & Test"

on:
  pull_request:
    branches: ["main"]
    paths:
      - "apps/sample-api/**"
      - "charts/sample-api/**"
      - ".github/workflows/ci.yml"
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"

jobs:
  python:
    name: Lint and Test (Python)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r apps/sample-api/requirements.txt
          pip install pytest flake8
      - name: Lint (flake8)
        run: |
          flake8 apps/sample-api/app apps/sample-api/tests
      - name: Run tests (pytest)
        run: |
          pytest apps/sample-api/tests -v --junitxml=pytest-results.xml
      - name: Upload test report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results
          path: pytest-results.xml

  helm:
    name: Lint Helm Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4
      - name: Helm lint
        run: |
          helm lint charts/sample-api
